### ISSUE TITLE
CS including SHALL be one of codes listed in the Value Set: NIP001. declaration not supported

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1012]
@robnist  on the following  CS in the updated 2.5.1 we need your input.

IZ-31: If RXA-20 is valued "CP" or "PA" then RXA-9.1 (admin notes) SHALL be valued one of the codes listed in NIP001 in the first occurrence of this field and optionally following repetition valued with a text notes.

In the ONC Tool it was built:

If RXA-20 (Completion Status) is valued and the value of RXA-20 (Completion Status) is one of List Values: 'CP','PA' then the value of RXA-9.1 (Identifier) SHALL be one of codes listed in the Value Set: NIP001.
If I try to build it like it was built in the ONC tool,  IGAMT-2 is not supporting **“SHALL be one of codes listed in the Value Set: NIP001.”**

**Comment by rob** [comment]
I will review!

**Comment by carolinerosin** [comment]
So for this one, we decided long ago that the ValueSet assertion was not going to be part of the UI.
Do we stand by this decision (and the user has to create the XML assertion) or do we want to revisit ?

I'm in favor of not adding the ValueSet assertion to the UI because user should avoid using it (because it does not have the same results as the value set validation module). We can discuss during the next IGAMT meeting.

**Comment by HossamT** [comment]
I am in favor too. @carolinerosin let's bring this up on Monday if we have time, and close it

**Comment by Abdelghani90** [comment]
@carolinerosin @HossamT Can I close this one?

**Comment by carolinerosin** [comment]
yeah let's close it, we're not adding the ValueSet assertion into the IGAMT UI. There's always the option of using the free-text + xml assertion for rare cases like that one. Regular users should not run into that (we'll stop them).
