### ISSUE TITLE
Predicate display bug when usage isn't even C(A/B)

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1064]
I'm not sure how I got this. Looks like there is a (R/X) that appears in my segments for field 6.
I noticed the same issue in several segments.

IG id is 5f1aedde9194be0006a1745a (LRI R1 DSTU R2 Septembre 2015)

![image](https://user-images.githubusercontent.com/13591511/88966914-0f6f8a80-d27b-11ea-8824-ded118cc4337.png)
![image](https://user-images.githubusercontent.com/13591511/88966960-2615e180-d27b-11ea-9edf-a2a3b016f7c8.png)
![image](https://user-images.githubusercontent.com/13591511/88967011-35952a80-d27b-11ea-9750-7811e60d0620.png)

**Comment by HossamT** [comment]
There is probably an issue in the data, I fixed the UI to not display a predicate if the usage is not C or CAB, but it just hides the predicate that should not be there in the first place @carolinerosin can you provide the ID of your IG that has this problem I can check to make sure the issue is in the data
