### ISSUE TITLE
DTF Library Status and Publication Date Requirements

### ISSUE THREAD

**Issue by robnist** [usnistgov/hl7-igamt#1082]
Upon a new library, all statuses are "Active". For existing libraries they can be made "Deprecated".

Per the specification I provided: "Publication Date indicates the date the DTF became active and, when the DTF is deprecated, the Publication Date indicates the date range when it was active. The latter date in the range gives the date it was deprecated."

Maybe this should be a toggle button or drop down for in general--maybe this is an easier way to implement. Default is "Active".

Both Status and Publication Date needs to be indicated in the export. See the SDTF specification I provided. I also attached decisions made for the SDTF. Make sure all of these have been handled.
[SDTF-feedback.docx](https://github.com/usnistgov/hl7-igamt/files/5066413/SDTF-feedback.docx)

**Comment by Abdelghani90** [comment]
Is there a difference between published ( Meaning that the user could start using the flavor) and Active?

**Comment by robnist** [comment]
Published is a concept at the library level. This has a lifecycle in IGAMT. Not sure if we discussed this. But something like, draft, published, superseded, etc. But only "published" can be used. May need to think about this a bit....but I thought we did this already.

Active and deprecated is a concept at each DTF level. This is a lifecycle (albeit simple) in the library.

**Comment by Abdelghani90** [comment]
It is more clear now! Please let me know if the following rules make sense.
1) All the flavors are "Active" by default unless the user chose to deactivate(deprecate) them.
2) If the user deactivate a flavor, all the the data type using it must be deactivated.
3) Even when a data type flavor is deprecated, its name will always remain reserved.
4) If a data type flavor was made deprecated after being published, its publication date would be displayed as a range when it was published:  [date of publication, date of when it became deprecated].
5) Filters could be eventually provided in the UI and configuration export,In order to provide a way to remove them from the toc or export.

**Comment by robnist** [comment]
All the flavors are "Active" by default unless the user chose to deactivate(deprecate) them.

1. If the user deactivate a flavor, all the the data type using it must be deactivated.
**Correct, in the DTF library. If an IG used it, it will remain. I expect very few deprecated DTF overtime.**
2. Even when a data type flavor is deprecated, its name will always remain reserved.
**Correct. Yes, just the status changes. It will affect EXPORT.**
3. If a data type flavor was made deprecated after being published, its publication date would be displayed as a range when it was published: [date of publication, date of when it became deprecated].
**Correct. range it was active.**
4. Filters could be eventually provided in the UI and configuration export,In order to provide a way to remove them from the toc or export.
**Correct.**
