### ISSUE TITLE
Derived IG: HTML Quick Export 

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1161]
**Describe the bug**
Exported IG is displaying Optional elements on a HTML Quick export.
Using Testing Scenario VI (derived) on smartinez290 account. 

**Expected behavior**
The default Export configuration excludes optional elements.

**Screenshots**
![image](https://user-images.githubusercontent.com/14842422/94576135-01ba8f00-0243-11eb-8b09-458eb37b1124.png)

**Comment by smartinez290** [comment]
@YoussefBouij I am seeing optional elements in the export using the IG Default Export configuration from the drop down after selecting HTML or Word.  I have a User Configuration that has the Optional checked, maybe is using that one.  I made the user configuration the default in the Configuration, but I was expecting to override it by selecting  IG Default Export configuration.

**Comment by smartinez290** [comment]
@YoussefBouij it looks like this is still an issue. I just exported a different IG using the default configuration. Optional elements are displayed at the message level but not at the segment level. 

![image](https://user-images.githubusercontent.com/14842422/98567418-e4cf9d80-227d-11eb-936e-b18e3920f702.png)

**Comment by Abdelghani90** [comment]
@YoussefBouij did you fixed this issue

**Comment by carolinerosin** [comment]
I'm not sure if what I'm testing is the correct thing (since it was Sandra's ticket) - but here what I did to test :
- exported an IG with "HTML quick export"
- checked what is exported in the message/segments/datatypes

I think Sandra's issue was that Optional element were exported (and should not). That was fixed, because I don't see any "O" element anymore (in the message structure, in the segments and in the datatypes).

I just have another question, and maybe this is something we should run by Rob (or maybe it was already answered). If an segment or datatype only contains optional elements, do we need to include it (with an empty table) ?

For example, here's what I see from the HTML quick export for my CE datatype :
![image](https://user-images.githubusercontent.com/13591511/105070093-cab9f480-5a50-11eb-8669-b15eb865ccc7.png)

Is that ok or do we want to remove the whole CE section (since everything within it is "O") ?

**Comment by Abdelghani90** [comment]
@YoussefBouij How hard is to hide this kind of empty tables?

**Comment by YoussefBouij** [comment]
I can look into it. I don't think we should remove the whole section though because when you click on the datatype in the TOC it should point to something. So maybe juste remove the table? But then that could be confusing to because at least with an empty table, the user know that the datatype is exported but there is nothing to display.

**Comment by Abdelghani90** [comment]
I agree. maybe we should add something like a placeholder (ex. No required elements ) We need to ask Rob about that.
