### ISSUE TITLE
Co-constraint table

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#735]
Created the table using **OBX**  as context in the message.
Added co-constraints
Created an OBX flavor
Created a co-constraint group using OBX-flavor
Applied OBX flavor in the message
Deleted the context in co-constraint table
Tried to import the CCG, the OBX-IZ flavor is not displayed, but I am able to see the OBX-IZ flavor when importing the group. 

I showed the issue to Abdel, he should be able to explain.

**Comment by Abdelghani90** [comment]
@HossamT I don't know if it is an error or a decision that you made, But the tree of the message showed when we want to select a segment is not displaying the flavor name. ( I guess @smartinez290 expected to see OBX_Z instead of OBX).

**Comment by HossamT** [comment]
@smartinez290 the tree only shows the structure not the flavors, I am not sure if in the old IGAMT it used to show the flavors too, I fear that adding the flavor to the tree will make it less readable, or should we add just the name of the flavor to the Segment? 

In my opinion, we should keep a consistent behavior and display just the structure because at that stage of entering requirements all you need to know is which OBX in your message structure you want to create co-constraints for, the flavor is not relevant at that point.

**Comment by HossamT** [comment]
Closed for inactivity
