### ISSUE TITLE
Validation - not getting expected invalid code system

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#844]
The validator is not triggering an error when an invalid code system is entered in a message.

**Comment by HossamT** [comment]
I need to see XML, to know if it's a validation issue.

**Comment by smartinez290** [comment]
[NIST-IGAMT-Profiling-Guide-5e62985a08bb3a000648c146_20200316_182421.zip](https://github.com/usnistgov/hl7-igamt/files/4339790/NIST-IGAMT-Profiling-Guide-5e62985a08bb3a000648c146_20200316_182421.zip)

**Comment by HossamT** [comment]
Can you provide details on which data element have you tested with?

**Comment by smartinez290** [comment]
PID-10.1 and PID-10.3 in this segment

PID|1||D26376273^^^NIST MPI^MR||Snow^Madelynn^Ainsley^^^^L|Lam^Morgan^^^^^M|20070706|F||2076-8^Native Hawaiian or Other Pacific Islander^CDCRECRRR|32 Prescott Street Ave^^Warwick^MA^02452^USA^L||^PRN^PH^^^657^5558563|||||||||H^non Hispanic or Latino^HL70189

The old validation triggers the following errors: 

Invalid Code System. Expected: 'CDCREC', Found: 'CDCRECRRR'
Code System : HL70292, not found in any of the Value Sets bindings
The value 'CDCRECRRR' at location Component PID-10.3 (Name of Coding System) is not member of the value set HL70396_IZ

GVT only generates one error:
The value '2076-8' at location Component PID-10.1 (Identifier) is not member of the value set CDCREC_E_IZ
--




Invalid Code System. Expected: 'CDCREC', Found: 'CDCRECRRR'
--

**Comment by smartinez290** [comment]
@HossamT did you understand what I tried to convey on this issue? I guess mistakenly added and additional line. 
What I tried to say is that GVT is only generating one error : The value '2076-8' at location Component PID-10.1 (Identifier) is not member of the value set CDCREC_E_IZ

When I run this message in the Immunization tool also generate the invalid code system error in addition of the code not found error.

**Comment by HossamT** [comment]
@smartinez290 thanks for the clarification, I was confused I understood it differently so I was waiting until I try to debug to answer, but now that you clarified the issue, I can give you an answer without debugging the tool.

in GVT you are using CDCREC_E_IZ on PID-10 which DOES NOT contain the value 2076-8 that why you get a code not found error.

In the IZ Tool you are using CDCREC_R_IZ on PID-10 which DOES contain the value 2076-8 but the code system is invalid that's why you get an invalid code system error.

Thanks,
Hossam.

**Comment by smartinez290** [comment]
@HossamT Thanks. I will close this one.
