### ISSUE TITLE
CS: RXA-6 (Administered Amount) shall contain a positive integer.

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#847]
Not generating an error when a negative integer is entered. 
[NIST-IGAMT-Profiling-Guide-5e62985a08bb3a000648c146_20200316_200226.zip](https://github.com/usnistgov/hl7-igamt/files/4340159/NIST-IGAMT-Profiling-Guide-5e62985a08bb3a000648c146_20200316_200226.zip)

**Comment by HossamT** [comment]
@Jungyubw please fix the format expression, use "Format" instead of "StringFormat" in the XML, StringFormat is a special exception that does not take a regular expression, instead, it takes either "SNOMED" or "LOINC" see doc at  https://github.com/usnistgov/v2-validation-legacy/releases/tag/1.4.2 

For this one since you are using a regular expression it should be a "Format" expression.

**Comment by Jungyubw** [comment]
Today I will fix it.

**Comment by Jungyubw** [comment]
Fixed
