### ISSUE TITLE
Internal PHINVADS v/s excluded from validation 

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#914]
I was expecting and error but I got an alert on an internal Phinvads v/s.
@HossamT are you still working on PhinVads validation?

Alert
![image](https://user-images.githubusercontent.com/14842422/79490948-aa559900-7feb-11ea-8178-d3a8181830e6.png)
Internal as defined in IGAMT
![image](https://user-images.githubusercontent.com/14842422/79491148-03253180-7fec-11ea-8a27-b7eda4f3f12e.png)

**Comment by HossamT** [comment]
What's the metadata on this VS? (Extensibility and Stability)

**Comment by smartinez290** [comment]
I created it As Flavor -- it said that it was internal.
This is metadata -- maybe because is open?
![image](https://user-images.githubusercontent.com/14842422/79491625-bc840700-7fec-11ea-8589-436db9c01c3e.png)
![image](https://user-images.githubusercontent.com/14842422/79491787-f523e080-7fec-11ea-9c1e-174c0a551af3.png)

**Comment by HossamT** [comment]
If you go to the value set definition sub-menu (where you can see the codes) you can find the metadata I am talking about in the "Value Set Attributes" accordion (the first one in the page)

If the value set is Open then we do not classify the detection as Error because the value set is open meaning it can have other codes that we are not aware of, so it's only an Alert

**Comment by smartinez290** [comment]
@HossamT Thanks. I am going to need the spec. to do QA. Do you have any documentation on this you can share with me? Thanks. I will close this Ticket.
