### ISSUE TITLE
Can't edit value set binding on segment

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#927]
The edit option is not available on this binding.

![image](https://user-images.githubusercontent.com/14842422/80213564-5c521e00-8607-11ea-8236-325fe6e27251.png)

This is on a  PV1 segment flavor I was creating.

**Comment by Abdelghani90** [comment]
this means that those locations should not allow value sets binding. You can see them because they are in the standard which might be an error. I would check with @carolinerosin

**Comment by carolinerosin** [comment]
@smartinez290 what is the segment you're looking at ?

**Comment by smartinez290** [comment]
@carolinerosin PV1

**Comment by carolinerosin** [comment]
@Abdelghani90 
So I checked in the standard, this the the table/value set that is supposed to be bind to PV1-7.1, PV1-8.1, PV1-9.1.
We need to fix that in the database (and possibly in all versions if they have this issue)
I suggest modifying the binding location to "1" if that is possible (I don't remember if that is possible for something that is not CE/CWE/CNE etc)
Otherwise change the binding so that it is a binding at the segment level and that targets the first component.
Does that make sense ?

**Comment by Abdelghani90** [comment]
@carolinerosin this is not a data issue as long as we see the right value set there. I have to update the configuration where I define the locations where we allow the value sets bindings. In the previous configuration, we don't allow binding for XCN.

**Comment by smartinez290** [comment]
@Abdelghani90 any status on this issue?

**Comment by Abdelghani90** [comment]
Fixed plus check

**Comment by smartinez290** [comment]
It does not look like is fixed. Am I missing something?

![image](https://user-images.githubusercontent.com/14842422/84523334-285db580-aca6-11ea-8f75-5de2ef1338d4.png)

**Comment by Abdelghani90** [comment]
Please refresh the tool and try again

**Comment by smartinez290** [comment]
Nice! it works now. Thanks.
